#!/usr/bin/env bash
# Bu skript localhost-u 127.0.0.2-yə, facebook.com-u isə 8.8.8.8-ə yönləndirir

# Mövcud localhost sətrini yenisi ilə əvəzləyirik və ya yoxdursa əlavə edirik
sudo sed -i 's/127.0.0.1\s*localhost/127.0.0.2 localhost/g' /etc/hosts

# Əgər hosts faylında artıq facebook.com qeydi yoxdursa, onu faylın sonuna əlavə edirik
if ! grep -q "facebook.com" /etc/hosts; then
    echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts > /dev/null
else
    # Əgər varsa, IP-sini 8.8.8.8-ə dəyişirik
    sudo sed -i 's/.*facebook.com/8.8.8.8 facebook.com/g' /etc/hosts
fi
